version: '2'

services:
  fnserver:
    container_name: fnserver-go
    image: artunsubasi/fnserver:latest
    environment:
      - FN_LOG_LEVEL=DEBUG
      - FN_LB_URL=http://localhost:8080
      - FN_API_SERVER_URL=http://localhost:8080
      - FN_ZEEBE_GATEWAY_URL=zeebe:26500
      - FN_IOFS_DOCKER_PATH=$PWD/iofs
      - FN_IOFS_PATH=/iofs
      - FDK_DEBUG=1
    volumes:
      - ./fn-data:/app/data
      - ./iofs:/iofs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
