version: '3.5'

# network static name required for FN_DOCKER_NETWORKS
networks:
  fn-network:
    name: fn-network
    driver: bridge

services:
  logstore:
    hostname: logstore
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - ./data/logstore:/data
    command: server /data
  db:
    image: "mysql:5.7.22"
    restart: always
    environment:
      - "MYSQL_DATABASE=funcs"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql:/var/lib/mysql
  mq:
    image: "redis"
    restart: always
  api:
    restart: always
    depends_on:
      - mq
      - db
      - logstore
    build:
      context: .
      dockerfile: images/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      FN_DB_URL: "mysql://root:root@tcp(db:3306)/funcs"
      FN_MQ_URL: "redis://mq:6379/"
      FN_LOGSTORE_URL: "s3://admin:password@logstore:9000/us-east-1/fnlogs"
      FN_PUBLIC_LB_URL: "http://127.0.0.1:8081"
  lb:
    restart: always
    depends_on:
      - db
      - runner
      - logstore
    build:
      context: .
      dockerfile: images/lb/Dockerfile
    ports:
      - "8081:8080"
    environment:
      FN_LOGSTORE_URL: "s3://admin:password@logstore:9000/us-east-1/fnlogs"
      FN_RUNNER_API_URL: "http://api:8080/"
      FN_RUNNER_ADDRESSES: "runner:9190"
  runner:
    restart: always
    build:
      context: .
      dockerfile: images/runner/Dockerfile
    networks:
      - default
      - fn-network
    environment:
      FN_IOFS_PATH: /app/data/iofs
      FN_IOFS_DOCKER_PATH: ${PWD}/data/iofs
      FN_DOCKER_NETWORKS: "fn-network"
    volumes:
      - ./data/iofs:/app/data/iofs
      - /var/run/docker.sock:/var/run/docker.sock
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    restart: always
    depends_on:
      - api
      - lb
      - runner
    volumes:
      - ./examples/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
  fnserver-ui:
    depends_on:
      - api
    image: fnproject/ui
    restart: always
    ports:
      - "4000:4000"
    environment:
      - FN_API_URL=http://fnserver:8080
